require 'webmock'

module FakeApiCalls
	def mock_twitter
		body = "{\"id\":2465478374,\"id_str\":\"2465478374\",\"name\":\"Juan David\",\"screen_name\":\"JdavidWhatsGood\",\"location\":\"\",\"profile_location\":null,\"description\":\"\",\"url\":null,\"entities\":{\"description\":{\"urls\":[]}},\"protected\":false,\"followers_count\":17,\"friends_count\":25,\"listed_count\":0,\"created_at\":\"Sun Apr 27 03:33:24 +0000 2014\",\"favourites_count\":3,\"utc_offset\":null,\"time_zone\":null,\"geo_enabled\":false,\"verified\":false,\"statuses_count\":6,\"lang\":\"en\",\"status\":{\"created_at\":\"Thu Apr 23 02:31:26 +0000 2015\",\"id\":591066820536356864,\"id_str\":\"591066820536356864\",\"text\":\"I guess chemistry is true. But I don't know if it's the Hennessy or you.\",\"source\":\"\\u003ca href=\\\"http://twitter.com\\\" rel=\\\"nofollow\\\"\\u003eTwitter Web Client\\u003c/a\\u003e\",\"truncated\":false,\"in_reply_to_status_id\":null,\"in_reply_to_status_id_str\":null,\"in_reply_to_user_id\":null,\"in_reply_to_user_id_str\":null,\"in_reply_to_screen_name\":null,\"geo\":null,\"coordinates\":null,\"place\":null,\"contributors\":null,\"is_quote_status\":false,\"retweet_count\":0,\"favorite_count\":0,\"entities\":{\"hashtags\":[],\"symbols\":[],\"user_mentions\":[],\"urls\":[]},\"favorited\":false,\"retweeted\":false,\"lang\":\"en\"},\"contributors_enabled\":false,\"is_translator\":false,\"is_translation_enabled\":false,\"profile_background_color\":\"C0DEED\",\"profile_background_image_url\":\"http://abs.twimg.com/images/themes/theme1/bg.png\",\"profile_background_image_url_https\":\"https://abs.twimg.com/images/themes/theme1/bg.png\",\"profile_background_tile\":false,\"profile_image_url\":\"http://pbs.twimg.com/profile_images/460263313423622144/59pqmNwF_normal.jpeg\",\"profile_image_url_https\":\"https://pbs.twimg.com/profile_images/460263313423622144/59pqmNwF_normal.jpeg\",\"profile_link_color\":\"0084B4\",\"profile_sidebar_border_color\":\"C0DEED\",\"profile_sidebar_fill_color\":\"DDEEF6\",\"profile_text_color\":\"333333\",\"profile_use_background_image\":true,\"has_extended_profile\":false,\"default_profile\":true,\"default_profile_image\":false,\"following\":false,\"follow_request_sent\":false,\"notifications\":false}"
		stub_request(:get, "https://api.twitter.com/1.1/users/show.json?screen_name=abinichole").
				          to_return(:status => 200, :body => body, :headers => {})
	end
end
