# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 848a4bb1d7c82cb713b9807b0dad0a645a8c5127bd86815b49869d549165b35c7ba568688c2d9b143920b195f21212326e2498caf511a772a778ecc81f8b3d2a

test:
  secret_key_base: 43795404db528f1161f6135af7111e5aae450ed98951b2b5466648a4e89b09f6b380df4b67f0905de73e76b60133664d0c7b7bc937761334bb491877a25619a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
